spring.application.name=Java-Util


milos.davitkovic.java.utils.pdf.file.name.prefix=${PDF_FILE_NAME:MilosDavitkovic}
milos.davitkovic.java.utils.pdf.content-type=${PDF_CONTENT_TYPE:application/pdf}
milos.davitkovic.java.utils.pdf.resource.folder=${PDF_RESOURCE_FOLDER:/resources}
milos.davitkovic.java.utils.pdf.resource.folder.windows=${PDF_RESOURCE_FOLDER_WINDOWS:\\resources}
milos.davitkovic.java.utils.fonts.resource.folder=${FONT_RESOURCE_FOLDER:/resources}